export default {
  myPersonalSchedule: [
    {
      time: ['07:00', '12:00'],
      affair: [
        { name: '■ ■ Politics', done: 0 },
        { name: '■ ■ Calculus', done: 0 },
        { name: '一元函数微分', done: 0 },
        { name: '一元函数积分', done: 0 },
        { name: '向量代数与空间解析几何', done: 0 },
        { name: '多元函数微分', done: 0 },
        { name: '多元函数积分', done: 0 },
        { name: '无穷级数', done: 0 },
        { name: '微分方程', done: 0 },
      ],
      style: { 'background-color': 'rgb(255, 125, 212)' },
    },
    {
      time: ['14:00', '18:00'],
      affair: [
        { name: '■ ■ ■ ■', done: 0 },
        { name: '计算机组成原理', done: 0 },
        { name: '操作系统', done: 0 },
        { name: '计算机网络', done: 0 },
        { name: 'C++ / 数据结构', done: 0 },
        { name: 'C++ / 算法', done: 0 },
        { name: 'C++ / 内存结构', done: 0 },
        { name: 'C++ / WebServer', done: 0 },
      ],
      style: { 'background-color': 'rgb(125, 229, 255)' },
    },
    {
      time: ['21:00', '00:00'],
      affair: [
        { name: '■ ■ ■ Comprehension', done: 0 },
        { name: '■ ■ ■ Writing', done: 0 },
        { name: '■ ■ ■ sjUI / erpUI', done: 0 },
      ],
      style: { 'background-color': 'rgb(125, 255, 194)' },
    },
    {
      time: ['09:00', '18:00'],
      affair: [
        { name: '首页：图片广告支持底部导航圆点', done: 1 },
        { name: '首页：图文导航支持文字颜色', done: 1 },
        { name: '首页：图文导航图片宽度自定义', done: 1 },
        { name: '首页：支持右下角图片', done: 1 },
        { name: '首页：跳转美味不用等', done: 1 },
        { name: '■ ■ ■ ■ 7.14提测 ■ ■ ■ ■', done: 0 },
        { name: 'C端 x 综合信息管理', done: 1 },
        { name: '■ ■ ■ ■ 7.24提测 ■ ■ ■ ■', done: 0 },
        { name: 'CMS功能链接/搜索 支持目的地功能', done: 0 },
        { name: '■ ■ ■ ■ 7.31提测 ■ ■ ■ ■', done: 0 },
        { name: 'CMS 新增酒店搜索组件', done: 0 },
        { name: 'CMS Tab推荐位 支持所有列表样式', done: 0 },
        { name: 'CMS Tab推荐位 支持Tab切换', done: 0 },
        { name: 'CMS Tab推荐位 导航条样式变更 (待定)', done: 0 },
        { name: 'CMS 图片广告 标题支持2行', done: 0 },
        { name: 'CMS 图片广告 图片宽度变更 (待定)', done: 0 },
        { name: '■ ■ ■ ■ V1.3 8.14提测 ■ ■ ■ ■', done: 0 },
      ],
      style: { 'background-color': 'rgb(176,255,0)' },
    },
    {
      time: ['09:00', '18:00'],
      affair: [
        { name: '■ ■ ■ ■ 综合信息管理明细 ■ ■ ■ ■', done: 0 },
        { name: '短文本', done: 1 },
        { name: '文字富文本', done: 1 },
        { name: '电话', done: 1 },
        { name: '坐标定位', done: 1 },
        { name: '图片', done: 1 },
        { name: '日期', done: 1 },
        { name: '语音', done: 1 },
        { name: '视频', done: 1 },
        { name: '单项选择', done: 1 },
        { name: '多项选择', done: 1 },
        { name: '链接', done: 1 },
        { name: '多媒体富文本', done: 1 },
        { name: '■ ■ ■ ■ 7.24提测 ■ ■ ■ ■', done: 0 },
      ],
      style: { 'background-color': 'rgb(255,0,32)' },
    },
  ],
}
