export default {
    myPersonalSchedule: [
        {
            time: ['10:00', '12:00'],
            affair: [
                { name: '■ ■', done: 0 },
                { name: '一元函数微分', done: 0 },
                { name: '一元函数积分', done: 0 },
                { name: '向量代数与空间解析几何', done: 0 },
                { name: '多元函数微分', done: 0 },
                { name: '多元函数积分', done: 0 },
                { name: '无穷级数', done: 0 },
                { name: '微分方程', done: 0 },
            ],
            style: { 'background-color': 'rgb(255,112,0)' },
        },
        {
            time: ['14:00', '17:00'],
            affair: [
                { name: '■ ■ ■', done: 0 },
                { name: '计算机组成原理', done: 0 },
                { name: '操作系统', done: 0 },
                { name: '计算机网络', done: 0 },
                { name: 'C++ *数据结构应用', done: 0 },
                { name: 'C++ *算法应用', done: 0 },
                { name: 'C++ *电路与内存', done: 0 },
                { name: 'C++ *WebServer', done: 0 },
                { name: 'Sanji *Canvas3D', done: 0 },
                { name: 'Sanji *进销存', done: 0 },
                { name: 'Sanji *UI', done: 0 },
            ],
            style: { 'background-color': 'rgb(125, 229, 255)' },
        },
        {
            time: ['09:00', '18:00'],
            affair: [
                { name: '推迟 *综合信息管理', done: 0 },
                { name: '短文本', done: 1 },
                { name: '文字富文本', done: 1 },
                { name: '电话', done: 1 },
                { name: '坐标定位', done: 1 },
                { name: '图片', done: 1 },
                { name: '日期', done: 1 },
                { name: '语音', done: 1 },
                { name: '视频', done: 1 },
                { name: '单项选择', done: 1 },
                { name: '多项选择', done: 1 },
                { name: '链接', done: 1 },
                { name: '多媒体富文本', done: 1 },
                { name: '0724 CMS *酒店搜索组件', done: 1 },
                { name: '0731 黟县 景区指南H5', done: 1 },
                { name: '推迟 0731 CMS接口 *获取当前可跳转的 "目的地" 列表', done: 0 },
                { name: '推迟 0731 CMS接口 *获取当前模板页面的 "目的地"', done: 0 },
                { name: '推迟 0731 CMS *目的地功能', done: 0 },
                { name: '0807 CMSv1.3 *Tab推荐位 支持列表切换', done: 1 },
                { name: '0807 CMSv1.3 *Tab推荐位 小图/大图/列表/瀑布流/反列表样式', done: 1 },
                { name: '0807 CMSv1.3 *Tab列表 支持反列表样式', done: 1 },
                { name: '0807 CMSv1.3 *图片广告 支持 x1/3d/1.3/1.5/1.7/2.0/2.5/3.0张 样式', done: 1 },
            ],
            style: { 'background-color': 'rgb(0,176,255)' },
        },
    ],
}
